project:
  type: website

website:
  title: "ISSS608: Weather Pulse"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - icon: github
        href: https://github.com/sherylanntys/ISSS608-Project
    
    left:
      - text: "Project Proposal"
        href: Project Proposal/Project_Proposal.html
      - text: "Prototype"
        menu: 
          - text: "Time-Series"
            href: Project Modules/Time_Series.html
          - text: "Geospatial"
            href: link here
      - text: "Shiny App"
        menu: 
          - text: "Shiny App"
            href: https://isss608-weatherpulse.shinyapps.io/home/
          - text: "User Guide"
            href: link here
        
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

