project:
  type: website

website:
  title: "ISSS608: Weather Pulse"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - icon: github
        href: https://github.com/sherylanntys/ISSS608-Project
    
    left:
      - text: "Project Proposal"
        href: Project Proposal/Project_Proposal.html
      - text: "Exploratory/Confirmatory"
        menu: 
          - text: "Data Preparation"
            href: Project Modules/Data_Preparation.html
      - text: "Time-Series"
      - text: "Geospatial"
        
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

